#!/usr/bin/python3

import socket
import sys
from _thread import *
import select 
import re 

if len(sys.argv)!=2:
    print("Enter Format: server application ipaddress:port ")
    sys.exit()

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
data1 = (sys.argv[1])
data2=data1.split(':')
addr=str(data2[0])
port=int(data2[1])
s.bind((addr,port))
s.listen(100)
print('clients are connecting please wait...............')
clients=[]
clients.append(s)

def clientthread(connection,address):
    while True:
        
        try:
            nick=connection.recv(2048).decode('utf-8')
            nick1=nick.strip('NICK ')
            regex = re.compile('[@!#$%^&*()?/|}{~:]')
            
            if(regex.search(nick1) == None) and len(nick1)<=12 and 'NICK ' in nick :
                connection.sendall('OK'.encode('utf-8'))
                break
            elif len(nick1) or regex.search(nick1) != None:
                connection.sendall('ERROR: Nickname should not exceed 12 characters'.encode('utf-8'))
            else:
                connection.close()
                print(address[0]+" client has been disconnected")
                clients.remove(connection)
                del clients[connection]
                break
        except :
                break

        

    while True:
        try:
            if connection in clients:
                message = connection.recv(2048).decode('utf-8')
                message1=message.strip('MSG ')
                
            
                if not message:
                    connection.close()
                    print(address[0]+" client has been disconnected")
                    clients.remove(connection)
                    break 

                elif 'MSG ' not in message:
                    connection.sendall('Error: correct command message'.encode('utf-8'))
                else:

                
                    if len(message1)<=255 :
                    
                        flag=0
                        for i in message1[:-1]:
                            if ord(i)<31:
                            
                                flag = flag +1
                            
                            else:
                                pass
                    #else if and next elif        
                        if flag != 0:
                            connection.sendall('ERROR occured, dont use control characters'.encode('utf-8'))
                        else:
                            message_to_send = 'MSG '+nick1+' ' + message1[:-1]
                
                            broadcasting(message_to_send,connection,nick1)
                    elif len(message1) > 255 :
                        connection.sendall('ERROR:message length of the message should be 256 characters'.encode('utf-8'))
                   
                

        except KeyboardInterrupt:
            connection.close()
            break

def broadcasting(message,connection,nick1):
    for sockets in clients:
        if sockets!= s:
            try:
                sockets.sendall(message.encode('utf-8'))
            except KeyboardInterrupt:
                    clients.remove(sockets)
                    break



while True:
    connection,address=s.accept()
    
    connection.sendall('Hello 1'.encode('utf-8'))
    clients.append(connection)
    print(address[0]+" has connected")
    
    start_new_thread(clientthread,(connection,address))
    

connection.close()
s.close()